[env]
PKG_CONFIG_PATH="C:\\Program Files\\gstreamer\\1.0\\msvc_x86_64\\lib\\pkgconfig"
GST_PLUGIN_SCANNER="C:\\Program Files\\gstreamer\\1.0\\msvc_x86_64\\libexec\\gstreamer-1.0\\gst-plugin-scanner.exe"
RUST_BACKTRACE="1"