services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

    volumes:
      -  ./dbs/rmq_data:/var/lib/rabbitmq
  
  pg_timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=user
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"
    volumes:
      - ./dbs/postgres_data:/home/postgres/pgdata

  migrations:
    build: ../backend/migrations
    container_name: migrations
    depends_on:
      - rabbitmq
      - pg_timescaledb
    volumes:
      - ../backend/migrations/postgres/.env.docker:/migrations/postgres/.env

  a_core_service:
    build: ../backend/A_core_service
    container_name: a_core_service
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - migrations 
      - rabbitmq
      - pg_timescaledb
    volumes:
      - ../backend/A_core_service/.env.production:/app/.env.production

  b_identity_service:
    build: ../backend/B_identity_service
    container_name: b_identity_service
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - migrations
      - rabbitmq
      - pg_timescaledb
    volumes:
      - ../backend/B_identity_service/.env.production:/app/.env.production