services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

    volumes:
      -  ./dbs-only/rmq_data:/var/lib/rabbitmq
  
  pg_timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=user
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"
    volumes:
      - ./dbs-only/postgres_data:/home/postgres/pgdata
    
  clickhouse: # docker exec -it 21341234 clickhouse-client
    image: clickhouse/clickhouse-server:25.8
    environment:
      - CLICKHOUSE_PASSWORD=1234
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_DB=courses
    ports: 
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      
  # fake_cdn:
  #   image: nginx:1.29-alpine
  #   container_name: nginx_files
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./files:/var/www/files
  #   depends_on:
  #     - auth
  #   networks:
  #     - internal

  nginx:
    image: nginx:alpine
    container_name: static-nginx
    ports:
      - "8080:80"
    volumes:
      - ../backend/C_media_service/test:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  clickhouse_data:
  clickhouse_logs: